//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Std
{
    [Serializable]
    public class EmptyMsg : Message
    {
        public const string k_RosMessageName = "std_msgs/Empty";
        public override string RosMessageName => k_RosMessageName;


        public EmptyMsg()
        {
        }
        public static EmptyMsg Deserialize(MessageDeserializer deserializer) => new EmptyMsg(deserializer);

        private EmptyMsg(MessageDeserializer deserializer)
        {
#if ROS2
            // ROS 2 IDL inserts structure_needs_at_least_one_member in empty
            // structures. Fast CDR expects this byte after the CDR header.
            deserializer.Read(out byte unused);
#endif
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
#if ROS2
            serializer.Write((byte)0);
#endif
        }

        public override string ToString()
        {
            return "EmptyMsg: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
